// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function DownloadSync(arg1:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadSettings():Promise<settings.Data>;

export function SaveSettings(arg1:settings.Data):Promise<void>;

export function UploadSync():Promise<string>;
